# Generated by Django 4.2.4 on 2023-09-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raza', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'db_table': 'raza',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tamaño', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños',
                'db_table': 'tamaño',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('peso', models.CharField(default='0', max_length=30)),
                ('edad', models.IntegerField(default=0, verbose_name='Edad')),
                ('fecha_nacimiento', models.DateField(default='2000-01-01', verbose_name='Fecha de nacimiento')),
                ('Tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_citas.tamaño')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_citas.raza')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgendarCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_cita', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Baño', 'Baño'), ('Peluqueria', 'Peluqueria'), ('Baño y Peluqueria', 'Baño y Peluqueria')], max_length=100, verbose_name='Tipo cita')),
                ('Fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('Hora', models.TimeField(verbose_name='Hora de la cita')),
                ('Telefono', models.CharField(max_length=15, verbose_name='Número de contacto')),
                ('descripcion', models.TextField(default='', max_length=200, verbose_name='Descripcion')),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendarcitas_name', to='gestion_citas.mascota')),
            ],
            options={
                'verbose_name': 'Agendar cita',
                'verbose_name_plural': 'Agendar citas',
                'db_table': 'AgendarCita',
                'ordering': ['id'],
            },
        ),
    ]
