# Generated by Django 4.2.4 on 2023-09-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendarcita',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
