# Generated by Django 4.2.4 on 2023-09-21 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado de PQRS')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_pqrs', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo pqrs',
                'verbose_name_plural': 'Tipos pqrs',
                'db_table': 'tipo_pqrs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creacion', verbose_name='Fecha de creacion')),
                ('Descripcion', models.TextField(default='', max_length=500, verbose_name='Descripcion')),
                ('Respuesta', models.CharField(blank=True, max_length=150, null=True)),
                ('Estado_pqrs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PQRS.estado')),
                ('Tipo_pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PQRS.tipo_pqrs', verbose_name='Tipo de PQRS')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
