# Generated by Django 4.2.4 on 2023-09-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='Tipo_pqrs',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=100, verbose_name='Tipo cita'),
        ),
    ]
