# Generated by Django 4.2.4 on 2023-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQRS', '0002_alter_pqrs_tipo_pqrs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_pqrs',
        ),
        migrations.RemoveField(
            model_name='pqrs',
            name='create_at',
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='Tipo_pqrs',
            field=models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=100, verbose_name='Tipo pqrs'),
        ),
    ]
