# Generated by Django 4.2.4 on 2023-09-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tipo compra')),
                ('day', models.DateField(verbose_name='Fecha de la cita')),
                ('hour', models.TimeField(verbose_name='Hora de la cita')),
                ('phone', models.CharField(max_length=15, verbose_name='Numero de contacto')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
